<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.101.2"/>
    <PackageVersion Include="AWSSDK.S3" Version="4.0.102.5"/>
    <PackageVersion Include="CSharpFunctionalExtensions" Version="3.6.0"/>
    <PackageVersion Include="Dlyn.Core" Version="0.0.2"/>
    <PackageVersion Include="Dlyn.Framework" Version="0.0.2"/>
    <PackageVersion Include="Dlyn.SharedKernel" Version="0.0.1"/>
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.11"/>
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11"/>
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.11"/>
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.11"/>
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4"/>
    <PackageVersion Include="StyleCop.Analyzers" Version="1.1.118"/>
  </ItemGroup>
</Project>