<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>Dlyn.FileService.Contracts</PackageId>
    <Version>0.0.1</Version>
    <Authors>Delaynore</Authors>
    <Company>Delaynore</Company>
    <Description>Contracts for FileService project</Description>
    <RepositoryUrl>https://github.com/delaynore/educon-tech</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dlyn.SharedKernel" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
