<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Dlyn.Core"/>
    <PackageReference Include="Dlyn.Framework"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FileService.Contracts\FileService.Contracts.csproj"/>
    <ProjectReference Include="..\FileService.Domain\FileService.Domain.csproj"/>
  </ItemGroup>
</Project>
